### ISSUE TITLE
Problem building Docker

### ISSUE THREAD

**Issue by nataliaasaa** [berleon/keras_models#36]
Hey! I was trying for a while to buid the Docker using the instructions (make base-image) and I am getting a syntax error when docker runs pip3 to install the packages:
![image](https://user-images.githubusercontent.com/27959874/202720614-5e96fb39-ea2a-4cc1-8029-afe7feae1766.png)

I tried to figure out why and one reason could be the python version (3.5) that it's deprecated, but I don't seem to be able to update the version. Do you have any thoughts about this and how I can run the Docker?

Thanks.

**Comment by ls1xt** [comment]
Hi nataliaasaa, it is really difficult to say what is not working exactly. The code is just quite old. I can refer you to this code: https://github.com/nebw/rendergan_pytorch It is a reimplementation if this paper in PyTorch. If you open an issue there, newb might also be able to share the training code which must be somewhere in a Jupyter Notebook.

**Comment by nataliaasaa** [comment]
Thank you berleon, I'll do that.
