### ISSUE TITLE
Regarding the type of images as input

### ISSUE THREAD

**Issue by sudharavali** [berleon/keras_models#6]
Hello

Do you think it will yeild similar results if the model had to identify a quadcopter, instead of barcode images (and if the model was trained on 3d model of quadcopters instead of bar codes). Please let me know !

**Comment by ls1xt** [comment]
Hi Sudha,

it depends on how large the distortions are. If it is only the quadcopter and the background is mostly sky, I would be very optimistic.

**Comment by sudharavali** [comment]
All right I will keep that in mind. Thanks !
